name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Git tag or commit SHA to rollback to"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Deploy rollback version to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/app"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            # Add commands to restart your app/service, e.g.:
            pkill -f "python src/app.py" || true
            nohup python3 src/app.py &

      - name: Notify rollback success
        run: echo "Rollback to ${{ github.event.inputs.version }} complete"
